Privacy Policy
Introduction and Definition

This Privacy Policy sets out how we, Bruce Devices, use and protect your personal data that you provide to us, or that is otherwise obtained or generated by us, in connection with your use of Bruce App (the “Services”). For the purposes of this Privacy Policy, ‘we’, ‘us’ and ‘our’ refers to Bruce Devices, and ‘you’ refers to you, the user of the Services.
Principles

We follow simple principles when it comes to your data:

    Your data is used exactly as you expect
    Your data is not shared with anyone, at any time
    Your data does not leave your device without your explicit consent

Information you provide

Installed Apps. Bruce App requires accesses to all applications installed on your device in order to function. This information is originally accessed through the Android system, and may be stored on-device in order to allow customization of app features. This information is only used on-device, and is not shared with any third-party. If you choose to share a bug report, you may choose to send a list of your apps and some metadata to us. This information will only be used to diagnose and fix problems.

Managing your information. All information used by Bruce App is stored on-device, and can be managed through Bruce App application Settings, or through Android’s system controls.
How we share your information

We do not share any information at any time.
Updates

This privacy policy will be updated as needed so that it is accurate, current, and clear.
Contact Us

If you have questions about this Privacy Policy please contact contact@bruce.computer.

Effective as of Jul 12, 2025

Updated Jul 12, 2025
