#ifdef T_DISPLAY_S3
#include "../lilygo-t-display-s3/pins_arduino.h"
#elif T_EMBED_1101
#include "../lilygo-t-embed-cc1101/pins_arduino.h"
#elif T_EMBED
#include "../lilygo-t-embed-cc1101/pins_arduino.h"
#elif T_DECK
#include "../lilygo-t-deck/pins_arduino.h"
#elif T_LORA_PAGER
#include "../lilygo-t-lora-pager/pins_arduino.h"
#elif ARDUINO_M5STACK_CARDPUTER
#include "../m5stack-cardputer/pins_arduino.h"
#elif CYD_2432S028
#include "../CYD-2432S028/pins_arduino.h"
#elif ARDUINO_M5STACK_CORE
#include "../m5stack-core/pins_arduino.h"
#elif ARDUINO_M5STACK_CORES3
#include "../m5stack-cores3/pins_arduino.h"
#elif ARDUINO_M5STACK_CORE2
#include "../m5stack-core2/pins_arduino.h"
#elif ARDUINO_M5STICK_C_PLUS
#include "../m5stack-cplus1_1/pins_arduino.h"
#elif ARDUINO_M5STICK_C_PLUS2
#include "../m5stack-cplus2/pins_arduino.h"
#elif ESP32S3DEVKITC1
#include "../ESP-General/pins_arduino.h"
#elif SMOOCHIEE_BOARD
#include "../smoochiee-board/pins_arduino.h"
#elif XK404
#include "../xk404/pins_arduino.h"
#elif T_WATCH_S3
#include "../lilygo-t-watch-s3/pins_arduino.h"
#elif T_DISPLAY_S3_PRO
#include "../lilygo-t-display-s3-pro/pins_arduino.h"
#elif TTGO
#include "../lilygo-t-display-ttgo/pins_arduino.h"
#elif MARAUDER_TOUCH
#include "../marauder-touch/pins_arduino.h"
#elif MARAUDER_MINI
#include "../marauder-mini/pins_arduino.h"
#elif LILYGO_T_HMI
#include "../lilygo-t-hmi/pins_arduino.h"
#elif ESP32C5_DEVKITC_1_TFT
#include "../ESP32-C5-tft/pins_arduino.h"
#elif ESP32C5_DEVKITC_1
#include "../ESP32-C5/pins_arduino.h"
#endif
