#ifndef __LANG_PT_BR_H__
#define __LANG_PT_BR_H__

// Main Menu Items
#define LANG_WIFI "WiFi"
#define LANG_BLE "BLE"
#define LANG_RF "RF"
#define LANG_IR "IR"
#define LANG_RFID "RFID"
#define LANG_NRF24 "NRF24"
#define LANG_FM "FM"
#define LANG_FILES "Arquivos"
#define LANG_GPS "GPS"
#define LANG_SCRIPTS "Interpretador JS"
#define LANG_OTHERS "Outros"
#define LANG_CLOCK "Relógio"
#define LANG_CONNECT "Conectar"
#define LANG_CONFIG "Config"

// WiFi Menu
#define LANG_CONNECT_WIFI "Conectar WiFi"
#define LANG_WIFI_AP "WiFi AP"
#define LANG_DISCONNECT "Desconectar"
#define LANG_WIFI_ATKS "Ataques WiFi"
#define LANG_EVIL_PORTAL "Portal Malicioso"
#define LANG_LISTEN_TCP "Escutar TCP"
#define LANG_CLIENT_TCP "Cliente TCP"
#define LANG_TELNET "TelNET"
#define LANG_SSH "SSH"
#define LANG_DPWO "DPWO"
#define LANG_RAW_SNIFFER "Sniffer Bruto"
#define LANG_SCAN_HOSTS "Escanear Hosts"
#define LANG_WIREGUARD "Wireguard"
#define LANG_BRUCEGOTCHI "Brucegotchi"
#define LANG_ADD_EVIL_WIFI "Adicionar WiFi Mal."
#define LANG_REMOVE_EVIL_WIFI "Remover WiFi Mal."
#define LANG_AP_INFO "Info do AP"

// BLE Menu
#define LANG_BLE_SCAN "Escanear BLE"
#define LANG_BLE_BEACON "Beacon BLE"
#define LANG_BLE_SPAM "Spam BLE"
#define LANG_BAD_BLE "Bad BLE"
#define LANG_MEDIA_COMMANDS "Comandos de Mídia"
#define LANG_BLE_KEYBOARD "Teclado BLE"

// RF Menu
#define LANG_SCAN_COPY "Escanear/Copiar"
#define LANG_CUSTOM_SUBGHZ "SubGhz Personalizado"
#define LANG_SPECTRUM "Espectro"
#define LANG_JAMMER "Bloqueador"
#define LANG_REPLAY "Reproduzir"

// IR Menu
#define LANG_TV_B_GONE "Desligar TVs"
#define LANG_CUSTOM_IR "IR Personalizado"
#define LANG_IR_READ "Ler IR"
#define LANG_IR_JAMMER "Bloqueador IR"

// RFID Menu
#define LANG_READ_TAG "Ler Tag"
#define LANG_WRITE_TAG "Gravar Tag"
#define LANG_CLONE_TAG "Clonar Tag"
#define LANG_EMULATE "Emular"
#define LANG_SCAN "Escanear"

// Others Menu
#define LANG_BADUSB "BadUSB"
#define LANG_LED_CONTROL "Controle de LED"
#define LANG_QR_CODE "Código QR"
#define LANG_MIC_SPECTRUM "Espectro do Mic"
#define LANG_USB_KEYBOARD "Teclado USB"

// Config Menu
#define LANG_BRIGHTNESS "Brilho"
#define LANG_DIM_TIME "Tempo Desligar"
#define LANG_ORIENTATION "Rotação"
#define LANG_UI_COLOR "Cor da Interface"
#define LANG_UI_THEME "Tema da Interface"
#define LANG_LED_COLOR "Cor do LED"
#define LANG_LED_BRIGHTNESS "Brilho do LED"
#define LANG_LED_BLINK_ON_OFF "Piscar LED Lig/Des"
#define LANG_SOUND_ON_OFF "Som Ligado/Desl."
#define LANG_STARTUP_WIFI "WiFi ao Iniciar"
#define LANG_STARTUP_APP "App ao Iniciar"
#define LANG_NETWORK_CREDS "Credenciais Rede"
#define LANG_SLEEP "Suspender"
#define LANG_FACTORY_RESET "Reset de Fábrica"
#define LANG_RESTART "Reiniciar"
#define LANG_TURN_OFF "Desligar"
#define LANG_DEEP_SLEEP "Suspensão Profunda"
#define LANG_ABOUT "Sobre"
#define LANG_DEV_MODE "Modo Desenvolvedor"
#define LANG_I2C_FINDER "Localizador I2C"
#define LANG_CC1101_PINS "Pinos CC1101"
#define LANG_NRF24_PINS "Pinos NRF24"
#define LANG_SDCARD_PINS "Pinos SDCard"
#define LANG_LANGUAGE "Idioma"

// Common Messages
#define LANG_BACK "Voltar"
#define LANG_SELECT "Selecionar"
#define LANG_CANCEL "Cancelar"
#define LANG_SAVE "Salvar"
#define LANG_DELETE "Excluir"
#define LANG_ERROR "Erro"
#define LANG_SUCCESS "Sucesso"
#define LANG_LOADING "Carregando"
#define LANG_PRESS_ANY_KEY "Pressione qq tecla"
#define LANG_CONNECTING "Conectando"
#define LANG_CONNECTED "Conectado"
#define LANG_DISCONNECTED "Desconectado"
#define LANG_SCANNING "Escaneando"
#define LANG_DONE "Concluído"
#define LANG_FAILED "Falhou"
#define LANG_SAVED "Salvo"
#define LANG_NO_SD_CARD "Sem Cartão SD"
#define LANG_FILE_NOT_FOUND "Arquivo não encontrado"
#define LANG_DISABLED "Desabilitado"
#define LANG_ENABLE "Habilitar"
#define LANG_DISABLE "Desabilitar"

// Settings strings
#define LANG_DEFAULT "Padrão"
#define LANG_WHITE "Branco"
#define LANG_RED "Vermelho"
#define LANG_GREEN "Verde"
#define LANG_BLUE "Azul"
#define LANG_LIGHT_BLUE "Azul Claro"
#define LANG_YELLOW "Amarelo"
#define LANG_MAGENTA "Magenta"
#define LANG_ORANGE "Laranja"
#define LANG_CUSTOM_UI_COLOR "Cor Personalizada"
#define LANG_INVERT_COLOR "Inverter Cor"
#define LANG_SOUND_OFF "Som desligado"
#define LANG_SOUND_ON "Som ligado"
#define LANG_LED_BLINK_OFF "Piscar LED deslig."
#define LANG_LED_BLINK_ON "Piscar LED ligado"

#endif
