#ifndef __LANG_EN_H__
#define __LANG_EN_H__

// Main Menu Items
#define LANG_WIFI "WiFi"
#define LANG_BLE "BLE"
#define LANG_RF "RF"
#define LANG_IR "IR"
#define LANG_RFID "RFID"
#define LANG_NRF24 "NRF24"
#define LANG_FM "FM"
#define LANG_FILES "Files"
#define LANG_GPS "GPS"
#define LANG_SCRIPTS "JS Interpreter"
#define LANG_OTHERS "Others"
#define LANG_CLOCK "Clock"
#define LANG_CONNECT "Connect"
#define LANG_CONFIG "Config"

// WiFi Menu
#define LANG_CONNECT_WIFI "Connect Wifi"
#define LANG_WIFI_AP "WiFi AP"
#define LANG_DISCONNECT "Disconnect"
#define LANG_WIFI_ATKS "Wifi Atks"
#define LANG_EVIL_PORTAL "Evil Portal"
#define LANG_LISTEN_TCP "Listen TCP"
#define LANG_CLIENT_TCP "Client TCP"
#define LANG_TELNET "TelNET"
#define LANG_SSH "SSH"
#define LANG_DPWO "DPWO"
#define LANG_RAW_SNIFFER "Raw Sniffer"
#define LANG_SCAN_HOSTS "Scan Hosts"
#define LANG_WIREGUARD "Wireguard"
#define LANG_BRUCEGOTCHI "Brucegotchi"
#define LANG_ADD_EVIL_WIFI "Add Evil Wifi"
#define LANG_REMOVE_EVIL_WIFI "Remove Evil Wifi"
#define LANG_AP_INFO "AP info"

// BLE Menu
#define LANG_BLE_SCAN "BLE Scan"
#define LANG_BLE_BEACON "BLE Beacon"
#define LANG_BLE_SPAM "BLE Spam"
#define LANG_BAD_BLE "Bad BLE"
#define LANG_MEDIA_COMMANDS "Media Commands"
#define LANG_BLE_KEYBOARD "BLE Keyboard"

// RF Menu
#define LANG_SCAN_COPY "Scan/Copy"
#define LANG_CUSTOM_SUBGHZ "Custom SubGhz"
#define LANG_SPECTRUM "Spectrum"
#define LANG_JAMMER "Jammer"
#define LANG_REPLAY "Replay"

// IR Menu
#define LANG_TV_B_GONE "TV-B-Gone"
#define LANG_CUSTOM_IR "Custom IR"
#define LANG_IR_READ "IR Read"
#define LANG_IR_JAMMER "IR Jammer"

// RFID Menu
#define LANG_READ_TAG "Read Tag"
#define LANG_WRITE_TAG "Write Tag"
#define LANG_CLONE_TAG "Clone Tag"
#define LANG_EMULATE "Emulate"
#define LANG_SCAN "Scan"

// Others Menu
#define LANG_BADUSB "BadUSB"
#define LANG_LED_CONTROL "LED Control"
#define LANG_QR_CODE "QR Code"
#define LANG_MIC_SPECTRUM "Mic Spectrum"
#define LANG_USB_KEYBOARD "USB Keyboard"

// Config Menu
#define LANG_BRIGHTNESS "Brightness"
#define LANG_DIM_TIME "Dim Time"
#define LANG_ORIENTATION "Orientation"
#define LANG_UI_COLOR "UI Color"
#define LANG_UI_THEME "UI Theme"
#define LANG_LED_COLOR "LED Color"
#define LANG_LED_BRIGHTNESS "LED Brightness"
#define LANG_LED_BLINK_ON_OFF "Led Blink On/Off"
#define LANG_SOUND_ON_OFF "Sound On/Off"
#define LANG_STARTUP_WIFI "Startup WiFi"
#define LANG_STARTUP_APP "Startup App"
#define LANG_NETWORK_CREDS "Network Creds"
#define LANG_SLEEP "Sleep"
#define LANG_FACTORY_RESET "Factory Reset"
#define LANG_RESTART "Restart"
#define LANG_TURN_OFF "Turn-off"
#define LANG_DEEP_SLEEP "Deep Sleep"
#define LANG_ABOUT "About"
#define LANG_DEV_MODE "Dev Mode"
#define LANG_I2C_FINDER "I2C Finder"
#define LANG_CC1101_PINS "CC1101 Pins"
#define LANG_NRF24_PINS "NRF24  Pins"
#define LANG_SDCARD_PINS "SDCard Pins"
#define LANG_LANGUAGE "Language"

// Common Messages
#define LANG_BACK "Back"
#define LANG_SELECT "Select"
#define LANG_CANCEL "Cancel"
#define LANG_SAVE "Save"
#define LANG_DELETE "Delete"
#define LANG_ERROR "Error"
#define LANG_SUCCESS "Success"
#define LANG_LOADING "Loading"
#define LANG_PRESS_ANY_KEY "Press any key"
#define LANG_CONNECTING "Connecting"
#define LANG_CONNECTED "Connected"
#define LANG_DISCONNECTED "Disconnected"
#define LANG_SCANNING "Scanning"
#define LANG_DONE "Done"
#define LANG_FAILED "Failed"
#define LANG_SAVED "Saved"
#define LANG_NO_SD_CARD "No SD Card"
#define LANG_FILE_NOT_FOUND "File not found"
#define LANG_DISABLED "Disabled"
#define LANG_ENABLE "Enable"
#define LANG_DISABLE "Disable"

// Settings strings
#define LANG_DEFAULT "Default"
#define LANG_WHITE "White"
#define LANG_RED "Red"
#define LANG_GREEN "Green"
#define LANG_BLUE "Blue"
#define LANG_LIGHT_BLUE "Light Blue"
#define LANG_YELLOW "Yellow"
#define LANG_MAGENTA "Magenta"
#define LANG_ORANGE "Orange"
#define LANG_CUSTOM_UI_COLOR "Custom Ui Color"
#define LANG_INVERT_COLOR "Invert Color"
#define LANG_SOUND_OFF "Sound off"
#define LANG_SOUND_ON "Sound on"
#define LANG_LED_BLINK_OFF "Led Blink off"
#define LANG_LED_BLINK_ON "Led Blink on"

#endif
